### ISSUE TITLE
Power supply

### ISSUE THREAD

**Issue by caracolmaker** [peekpt/MicroSolderingStation#2]
What power source do you use for that project? I have a house from an old 12v and 1.5 amp laptop, would it work for the project?

**Comment by peekpt** [comment]
Use platformio ide, open the folder and main.cpp then then plug your
Arduino and run

Na(o) quinta, 13/12/2018, 19:34, caracolmaker <notifications@github.com>
escreveu:

**Comment by caracolmaker** [comment]
What power supply do you use for this proyect.?

**Comment by peekpt** [comment]
I use a simple 12v 2A wall charger, don't go over 14v the amp of the
Arduino uno can burn

caracolmaker <notifications@github.com> escreveu no dia sábado, 15/12/2018
à(s) 18:18:

**Comment by caracolmaker** [comment]
Thank you
